### ISSUE TITLE
Add onset-contingent analysis

### ISSUE THREAD

**Issue by brockf** [jwdink/eyetrackingR#1]
from Yurovksy & Frank (2015, Developmental Science)

**Comment by jwdink** [comment]
Plotting function is written. If there's any analysis function to write, this issue should be re-opened.

**Comment by brockf** [comment]
The corresponding analysis is the time of the first switch. That is, for each trial: (1) what AOI were they focused on at window onset and, (2) what time did they first switch away from this window? One can then do a within-subjects analysis on switching times between different AOI starting points -- i.e., an onset contingent analysis of fixation switch times. 

Does that makes sense? I don't think Yurovsky and Frank (2015) did it, but this is the logic behind most Fernald et al analyses.

**Comment by jwdink** [comment]
Got it!
