### ISSUE TITLE
Add Maris and Oostenveld analysis for non-parametric time series

### ISSUE THREAD

**Issue by jwdink** [jwdink/eyetrackingR#12]

**Comment by brockf** [comment]
We should call these "cluster analyses" -- you should also read about the "sum t" and see whether this p-value idea is better/worse than the sum-t test.

**Comment by jwdink** [comment]
OK, I gotcha. It looks like the M&O paper is an example of the more general bootstrapping technique, and then for the specific version used for time-series, they're actually going off of the "clustering of adjacent time-samples" technique from http://www.ai.mit.edu/events/talks/fMRI/papers/permutation_tests2.pdf

**Comment by jwdink** [comment]
I'm having trouble finding anything on the "sum t" test.

Also, I think you were right that the cluster-based technique not being as sophisticated as I thought it was

**Comment by brockf** [comment]
This paper refers to both sum-t and Maris & Oostenveld:

http://pubman.mpdl.mpg.de/pubman/item/escidoc:1212553/component/escidoc:1587255/RMPH_Neuropsychologia2013.pdf

**Comment by jwdink** [comment]
Brainstorming note to self:
make selection of t-threshold less arbitrary by finding values where derivative for f(t) = num_clusters is closer to zero
