### ISSUE TITLE
ggplot2 dev

### ISSUE THREAD

**Issue by hadley** [jwdink/eyetrackingR#36]
I see the following problems:

```
checking R code for possible problems ... NOTE
plot.time_sequence_data: warning in stat_summary(fun.dat = mean_se,
  geom = "ribbon", alpha = 0.25, colour = NA): partial argument match
  of 'fun.dat' to 'fun.data'
```

**Comment by jwdink** [comment]
Hi,

I actually just fixed that problem today, so you may just be running it on an "old" (i.e., a few hours old) version. Running R CMD CHECK on the current version doesn't give (me) that error.
