### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by geraldstanje** [jwdink/eyetrackingR#52]
Hi,

which eye tracking systems have you used in your research? Can you recommend me some systems which can be used with eyetrackingR?

Thanks,
Gerald

**Comment by jwdink** [comment]
Hi Gerald,

Depends on your goals. I've used an SR Research Eyelink 1000 for research with adults; @brockf has used a Tobii system for research with children. This is somewhat outside of the scope for issues with the code/package itself, however, so I'm going to close this issue.

Cheers,
Jacob
