### ISSUE TITLE
Average fixations to two AOIs

### ISSUE THREAD

**Issue by tessvdz** [jwdink/eyetrackingR#55]
Hi there again, 

I wonder whether I can also combine the fixations to the two distractor images and take the average of these two as one AOI. 
In that way I would be able to easily compare the fixations to the target vs. the distractors. 

I considered some things but it seems that in the way the data is set up in eyetrackingR there is no average, as the absolute number of fixations to the distractors is higher if you combine the two distractors in one column (e.g. DistAOI consisting of fixations to Distractor AOI1 and Distractor AOI2). 

I already ran some linear mixed effect models where the AOI column gives for each point in time (each row) the AOI the participants fixated on (e.g. Target = 1, Distractor 1 =2, Distractor 2 = 3). But now I will compare the fixations to the Target and the Distractors binary.
Therefore it seems that I cannot use this AOI column as it will count the absolute number of Distractor 1 and Distractor 2 together rather than the mean of these two distractors.  

My intuition would be to make an average of the proportions (of Distractor AOI1 and Distractor AOI2). Do you have any ideas or suggestions? 

Let me know if anything is unclear. 
Thank you in advance.

Best, 

Tess

**Comment by jwdink** [comment]
Hi Tess,

Apologies for the delay. Can you provide a [reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)? I'm not entirely clear what kind of model you're running, and what kind of model you'd like to be running.

Best,
Jacob
