### ISSUE TITLE
Value of elog in make_time_sequence_data for NA gaze

### ISSUE THREAD

**Issue by shotsuji** [jwdink/eyetrackingR#57]
Hi,
I've been experimenting with your package - great job in putting this together and documenting it.
When I make_time_sequence_data and have a time bin with NA gazes exclusively (OnTarget=NA, AWAY=TRUE), I do get values of Elog=0, but NA for all other measures - shouldn't this also be NA for elog, and if not, why?
Sho

**Comment by jwdink** [comment]
thanks!

**Comment by jwdink** [comment]
Fixed in https://github.com/jwdink/eyetrackingR/commit/921e518148d85af4232caed921fe3acf46820543
