### ISSUE TITLE
Write paper

### ISSUE THREAD

**Issue by brockf** [jwdink/eyetrackingR#8]

**Comment by brockf** [comment]
Behavioural Research Methods seems like a great outlet. See, for example, this paper on a Matlab library for eye-tracking analysis:

http://download.springer.com/static/pdf/651/art%253A10.3758%252FBF03195488.pdf?originUrl=http%3A%2F%2Flink.springer.com%2Farticle%2F10.3758%2FBF03195488&token2=exp=1438186196~acl=%2Fstatic%2Fpdf%2F651%2Fart%25253A10.3758%25252FBF03195488.pdf%3ForiginUrl%3Dhttp%253A%252F%252Flink.springer.com%252Farticle%252F10.3758%252FBF03195488*~hmac=b003158a7b9990dcb15380c68e6cadb34d52a88a01232f700c81644c0b67e66e

**Comment by brockf** [comment]
Strengths we must mention:
- R
- Very fast, optimized
- Very ease to use

Things we must do:
- Simple walkthrough of an analysis showing convergent results across types
- Short introduction to each analysis, with example papers

**Comment by brockf** [comment]
Structure:
- You have some data.
- Analysis can be overwhelming, but it's actually simple: Clean, Shape, Visualize, and Analyze.
- But how you shape, visualize, and analyze depends on your question. Here we describe the kinds of questions you might have, provide a conceptual overview of their respective answers, and implement an analysis using an open-source R package.

Themes:
- Optimized for big data
- Visualize every step of the way -- never lose sight of your data, literally
- Combination of approaches is sometimes best -- see if different methods give you the same answer
- Many eye-tracking studies yield measures that violate assumptions for common statistical tests (e.g., proportions). This can be addressed in two keyways: (1) changing your dependent variable (logit, empirical logit, arcsine) or, (2) using non-parametric bootstraps. We implement both techniques.

**Comment by jwdink** [comment]
I'm closing this, as it seems awkward to include on the public issues forum.
