### ISSUE TITLE
should our plots use rollapply instead of time bins?

### ISSUE THREAD

**Issue by jwdink** [jwdink/eyetrackingR#9]
http://www.inside-r.org/packages/cran/zoo/docs/rollapply

**Comment by brockf** [comment]
What's the benefit here? Linking them to time bins is conceptually simpler, of course.

**Comment by jwdink** [comment]
benefit = frank & yurovsky did it, so it must be better? but no, not necessarily any benefit, just wanted to make sure it was on the table. I think I agree it would complicate things: we'd basically have one method for plotting (rolling windows) and another method for analysis (bins), which seems problematic
